### PR TITLE
Support Flutter v2.5

### PR DESCRIPTION
**Pull request by Dimdron**

### CODE REVIEW

**Comment by Dimdron** [comment]
https://github.com/appspector/flutter-plugin/issues/48

**Comment by sergeyzenchenko** [comment]
@CodiumAI-Agent /review

**Comment by sergeyzenchenko** [comment]
@CodiumAI-Agent /improve

**Comment by sergeyzenchenko** [comment]
@CodiumAI-Agent /ask does this PR affect CI setup?

**Comment by sergeyzenchenko** [comment]
@CodiumAI-Agent /ask how it looks like from performance perspective?

**Pull request merged**
